#-----------------------------------Open the config with NotPad ++ for better results-----------------------------------
#                                                                                     *.,                     /%
#                                                                                  ,/  ,.                    #./
#                                                                         (*,  ,..&*,..,.                  *%((
#                                                                        ,%//*(,.&#(***,,./.. ,(,.      .(/##(,
#                                                                     .*(#%(,,*.%%#((///*,(%%/#*./  /,./((###(
#                                                       . ,,*    .    /,.,./&#/(&%##(####&%&&(&(##%,*#%###%%(,
#                                                   ,#,.*  / ., .(/ ,,*.**.*&%%&&%%#####&/%#&%%(((#*/##*%%%#(
#                                          ,/#.(**.,....*&*#,*/*/(/***(/*.%%#(/@%%%#####%**#/&%%(,/(%,.,,*%%,
#                                         /%  ,***.*/**.*(@##(/(/(&&#/*/#(*####&&%%%##%#(/,.*((*(&%%//#*,*,...
#                               ,%%%%%#/,      ,***#,,((((&#&#(/##(....&%###(#*/%%###%*** /#(. .,,****#/.*%,*
#                            ./.... .*,,.,,***,,.*/(#%*(#(%%%/*(*,.(%%#((/*/(,,. #%#(. .....*(/(   * ..  (., .
#                                     ..,*,,*(/*(/(##%&(#(#*#(,./###(/***///,,....,,.  .,,,, .,..,    .   /(, ,,
#                             .     */*######/**%#*(&(%%/*/(,,(((///*,,,,*(*. .,,/.....,*///,,,,,(,..,.,,****
#                        ,,.,../&/.  ,*/#%#%%##%%%%#/&##,,,,#/***,,......,&.  . .#,,..,**/((***,**,,    ,///((
#                          ., .,,. .#(  .*/%&&&&%&%%%*/*,,((,,,,,,. . ..  #  .  ./,..,,///&//***          /#%%%*
#                                   ,(.//,/(#%&&&%&#%****&*,,,,.....      , *  */*,,,**#/(##/**/            (%####.
#                          ,,.    ....,,*/(##((&&%%%***%/.,,,,.,.,*.       #   .**...*#%&&#///,.             /(#%&&#.
#                              . ,.*(%%%#/##(###%%(**/&*.,,,,.,****,     ,(..     /%%%&&%%###/*..            .##%&&%*
#                       .. *(*/*... .,*(#(#%#&####/*%#*,*,,,,,*////,    *%,,.      /&@@@%&@%*,  .,             #%@&&*
#                      ,,%*,.   .,*(&&%%##(#&#%(#(/@(/**,,,,***///*.   .&*,.       **&&&&@&&%*    ..            /@@*
#                     ,%//,*/////////(%&&&%%((((((@******,,*////*.     @*.          *(//##%#%&,    .,            ,(
#                    ,(./*,,,,**/#%#**(#%&@&((((#&****,*//((#((((,.   ,&*.           *      //.  ...,.          *,
#                    .  ,#(/.**,***/##,/(#@&//(#&(***,*/(((##(((/,.   *#*.                   /,    ....         .
#                    ,**(/**,,%/**//%%##(%%(/((@(*/,,,**((/(((#/,..   .#/*.    ....     *     .,    ..,,         .
#                    ./(,..,#,..*#//#%#((##(((&(/*/,,**(((#((((/,..   .(/***,,.,,,..    ..*. .//     ..,/        (
#                    ,,.  .(.,/((.,,*%#(((///#(////*(((#%#((((((*****,..((/(//*,,,,,.. .,,,//##,        *.        (
#                    ..   # (%/*,,,,*%##((/**/(//(//(##(#%#####(/****, ..%(//*****,,.. .**(##((.        .(        *.
#                    .    #/# *..,,,*%%(///**//(((//(##%%#%###%#/////   ..(%(((/***,,,..*#%%#((##       ..#        (
#                    ,   * /* ..,,,,*%#((///*///((((%%%%%%####(#((/#/,,  .,,&###((/////((%&#((((#,      ,,,/       .,
#                          *.*...,,,,/#(//////(((##&&&&%%%%##%#*((%//,.  ,*,,/@%%%%##((#%&%%####%*     .,,,,,       ,
#                       ,  ,,..  .,, ,/(#//**/((##%%&&&&%%%%%%%*.%(((**,*//***/#/#@&&&&&%%#%(#%#(,       ....       .
#                    ,.%/  ,  ..,,,..,*/#//(///(((#&&&&&&&%%##(*%.#(//*****,**(#*    .%&&%%&%%&(#%,        ...       (
#                       .  /.  ,,,,,,,.*#((##(#(((#%&@&&&&%%#%(%* *((///******(.,      .%&&&%#%&%%&/  ,      ..      .(
#                         ...    ,... ..,((#######&&&&&&%%%%%#%/.  .*//*/**//.%,          #&%%%#%%&/  .    ,,..      .,*
#                                         *%%%%%#%%&&&&&&%&&%%#*     .//(/// ,*.            #&%%%%,.     ,,%%,       ..,.
#                            ...           #%&&%&%%&%&%%%%%&##(,      .((((. *,,              .&&/,     ,@%&(.     ...,/.
#                                           ,  .&&@&&&%&&%&%#%/        ,(/   ,,.*               //.    .&@&%%(/*.....*/%.
#                                          .    /%%%%%&&&&&&%&/             .,,./               .*,     %@@&%###(*,,((#.
#                                        ,..     %%%%%%&&%%%&&             .*,,,,                .,.    (@@@@&%(#/(#%%
#                                         .       (&@@&&&&&%&&             (,,,#                   ,     %@@@&&%%%%&&
#                                                  ,#@@&&%&#*             #/**,#,                  /%&&&%#&&&&&&&&&&
#                                                 ....*%&&#,   ....      (/**,.(*.                  .#@@@&&&&&@#/*.

#                                           888888 888     888        d8888 888b    888
#                                           "88b 888     888       d88888 8888b   888
#                                           888 888     888      d88P888 88888b  888
#                                           888 888     888     d88P 888 888Y88b 888
#                                           888 888     888    d88P  888 888 Y88b888
#                                           888 888     888   d88P   888 888  Y88888
#                                           88P Y88b. .d88P  d8888888888 888   Y8888
#                                           888  "Y88888P"  d88P     888 888    Y888
#                                         .d88P
#                                        :d88P"
#                                        .88P"
#
#                               8888888b.  888      888     888  .d8888b.  8888888 888b    888
#                               888   Y88b 888      888     888 d88P  Y88b   888   8888b   888
#                               888    888 888      888     888 888    888   888   88888b  888
#                               888   d88P 888      888     888 888          888   888Y88b 888
#                               8888888P"  888      888     888 888  88888   888   888 Y88b888
#                               888        888      888     888 888    888   888   888  Y88888
#                               888        888      Y88b. .d88P Y88b  d88P   888   888   Y8888
#                               888        88888888  "Y88888P"   "Y8888P88 8888888 888    Y888

                                     #-------------------------------------------------#
                                     # Artifacted by Zago and my best friend Stephirio #
                                     #-------------------------------------------------#



#-------------------------------------------------------#
#   FIRST CUSTOMIZABLE HORSE || PERM: juan.first.juan   #
#-------------------------------------------------------#


First-Horse-NameVisible: true
First-Horse-Name: '&6[&cJUAN&6] &dof &b%first-horse-name%'
First-Horse-Glow: false
First-Horse-Color: true
Horse-Color: 'CHESTNUT'
#---------------the colors available are----------------#
#                                                       #
#   WHITE|BLACK|BROWN|CHESTNUT|CREAMY|DARK_BROWN|GRAY   #
#-------------------------------------------------------#
First-Horse-JumpStrength: true
First-Horse-Jump: 7.00
First-Horse-MaxHealth: true
First-Horse-SetMaxHealth: 40
First-Horse-Cost: 100.00

#inserire un gui
First-Horse-Swimming: true
First-Horse-Silent: true
First-Horse-Invincible: true
First-Horse-Mount: true
First-Horse-Player-Set-Owner: true
First-Horse-Give-Saddle: true
First-Horse-Give-Armor-Toggle: true
First-Horse-Give-Armor: 'DIAMOND_HORSE_ARMOR'

#-------------------------ROCKET-------------------------#
First-Rocket-Toggle: true
First-Rocket-Color: 'WHITE'



